<a href="https://colab.research.google.com/github/laresamdeola/Machine-Learning/blob/main/Auto_Insurance_in_Sweden_using_the_Random_Forest_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('Auto Insurance in Sweden 2.csv')
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [3]:
print(X)

[[108]
 [ 19]
 [ 13]
 [124]
 [ 40]
 [ 57]
 [ 23]
 [ 14]
 [ 45]
 [ 10]
 [  5]
 [ 48]
 [ 11]
 [ 23]
 [  7]
 [  2]
 [ 24]
 [  6]
 [  3]
 [ 23]
 [  6]
 [  9]
 [  9]
 [  3]
 [ 29]
 [  7]
 [  4]
 [ 20]
 [  7]
 [  4]
 [  0]
 [ 25]
 [  6]
 [  5]
 [ 22]
 [ 11]
 [ 61]
 [ 12]
 [  4]
 [ 16]
 [ 13]
 [ 60]
 [ 41]
 [ 37]
 [ 55]
 [ 41]
 [ 11]
 [ 27]
 [  8]
 [  3]
 [ 17]
 [ 13]
 [ 13]
 [ 15]
 [  8]
 [ 29]
 [ 30]
 [ 24]
 [  9]
 [ 31]
 [ 14]
 [ 53]
 [ 26]]


In [12]:
y = y.reshape(len(y), 1)
print(y)

[[392.5]
 [ 46.2]
 [ 15.7]
 [422.2]
 [119.4]
 [170.9]
 [ 56.9]
 [ 77.5]
 [214. ]
 [ 65.3]
 [ 20.9]
 [248.1]
 [ 23.5]
 [ 39.6]
 [ 48.8]
 [  6.6]
 [134.9]
 [ 50.9]
 [  4.4]
 [113. ]
 [ 14.8]
 [ 48.7]
 [ 52.1]
 [ 13.2]
 [103.9]
 [ 77.5]
 [ 11.8]
 [ 98.1]
 [ 27.9]
 [ 38.1]
 [  0. ]
 [ 69.2]
 [ 14.6]
 [ 40.3]
 [161.5]
 [ 57.2]
 [217.6]
 [ 58.1]
 [ 12.6]
 [ 59.6]
 [ 89.9]
 [202.4]
 [181.3]
 [152.8]
 [162.8]
 [ 73.4]
 [ 21.3]
 [ 92.6]
 [ 76.1]
 [ 39.9]
 [142.1]
 [ 93. ]
 [ 31.9]
 [ 32.1]
 [ 55.6]
 [133.3]
 [194.5]
 [137.9]
 [ 87.4]
 [209.8]
 [ 95.5]
 [244.6]
 [187.5]]


In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.25, random_state=0)
print(X_train)
print(y_train)

[[ 11]
 [ 41]
 [  7]
 [ 14]
 [  7]
 [  9]
 [ 41]
 [  8]
 [ 13]
 [ 60]
 [ 24]
 [  3]
 [ 31]
 [ 25]
 [  2]
 [  0]
 [ 57]
 [ 24]
 [  6]
 [ 29]
 [ 45]
 [ 23]
 [  7]
 [ 12]
 [  6]
 [ 53]
 [ 13]
 [ 30]
 [  4]
 [ 19]
 [ 11]
 [  8]
 [ 29]
 [ 23]
 [  3]
 [ 61]
 [ 17]
 [  9]
 [ 23]
 [ 10]
 [ 16]
 [  9]
 [124]
 [108]
 [ 15]
 [ 27]
 [ 55]]
[[ 57.2]
 [ 73.4]
 [ 27.9]
 [ 77.5]
 [ 48.8]
 [ 52.1]
 [181.3]
 [ 55.6]
 [ 89.9]
 [202.4]
 [137.9]
 [  4.4]
 [209.8]
 [ 69.2]
 [  6.6]
 [  0. ]
 [170.9]
 [134.9]
 [ 14.8]
 [133.3]
 [214. ]
 [ 39.6]
 [ 77.5]
 [ 58.1]
 [ 50.9]
 [244.6]
 [ 31.9]
 [194.5]
 [ 12.6]
 [ 46.2]
 [ 23.5]
 [ 76.1]
 [103.9]
 [ 56.9]
 [ 13.2]
 [217.6]
 [142.1]
 [ 48.7]
 [113. ]
 [ 65.3]
 [ 59.6]
 [ 87.4]
 [422.2]
 [392.5]
 [ 32.1]
 [ 92.6]
 [162.8]]


In [14]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=100)
regressor.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor()

In [15]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[136.94 152.8 ]
 [  8.88  39.9 ]
 [ 85.52 187.5 ]
 [ 61.4   93.  ]
 [ 35.28  14.6 ]
 [ 69.84 161.5 ]
 [ 11.56  38.1 ]
 [ 42.1   21.3 ]
 [214.73 248.1 ]
 [ 61.4   15.7 ]
 [ 11.56  11.8 ]
 [ 69.84  95.5 ]
 [138.28 119.4 ]
 [ 18.61  20.9 ]
 [ 77.16  98.1 ]
 [ 18.61  40.3 ]]


In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6474498596725324