In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [32]:
data = pd.read_csv('breast-cancer-clean.csv')
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 276 entries, 0 to 275
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   no-recurrence-events  276 non-null    object
 1   30-39                 276 non-null    object
 2   premeno               276 non-null    object
 3   30-34                 276 non-null    object
 4   0-2                   276 non-null    object
 5   no                    276 non-null    object
 6   3                     276 non-null    int64 
 7   left                  276 non-null    object
 8   left_low              276 non-null    object
 9   no.1                  276 non-null    object
dtypes: int64(1), object(9)
memory usage: 21.7+ KB


In [34]:
print(X)

[['40-49' 'premeno' '20-24' ... 'right' 'right_up' 'no']
 ['40-49' 'premeno' '20-24' ... 'left' 'left_low' 'no']
 ['60-69' 'ge40' '15-19' ... 'right' 'left_up' 'no']
 ...
 ['60-69' 'ge40' '20-24' ... 'right' 'left_up' 'no']
 ['40-49' 'ge40' '30-34' ... 'left' 'left_low' 'no']
 ['50-59' 'ge40' '30-34' ... 'left' 'left_low' 'no']]


In [36]:
print(X.shape, y.shape)

(276, 9) (276,)


In [37]:
from sklearn.preprocessing import OrdinalEncoder
ordinal = OrdinalEncoder()
X = ordinal.fit_transform(X)

In [38]:
print(X)

[[2. 2. 3. ... 1. 4. 0.]
 [2. 2. 3. ... 0. 1. 0.]
 [4. 0. 2. ... 1. 2. 0.]
 ...
 [4. 0. 3. ... 1. 2. 0.]
 [2. 0. 5. ... 0. 1. 0.]
 [3. 0. 5. ... 0. 1. 0.]]


In [39]:
print(X.shape)

(276, 9)


In [40]:
from sklearn.preprocessing import LabelEncoder
encode = LabelEncoder()
y = encode.fit_transform(y)

In [41]:
print(y.shape)

(276,)


In [42]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [6]:
# do the label encoders 
# do the one hot encoders
# split to training and test set
# feature scaling
# ann model
# add the input layer
# add the hidden layers
# compile the ann
# train the ann
# the predict
# accuracy score
# confusion matrix

In [11]:
y = encode.fit_transform(y)

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [45]:
ann = tf.keras.models.Sequential()

In [46]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [47]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [48]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [49]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [54]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 0s 5ms/step - loss: 0.3145 - accuracy: 0.8682
Epoch 2/100
7/7 [==============================] - 0s 6ms/step - loss: 0.3140 - accuracy: 0.8727
Epoch 3/100
7/7 [==============================] - 0s 2ms/step - loss: 0.3137 - accuracy: 0.8727
Epoch 4/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3134 - accuracy: 0.8727
Epoch 5/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3135 - accuracy: 0.8727
Epoch 6/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3131 - accuracy: 0.8727
Epoch 7/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3129 - accuracy: 0.8727
Epoch 8/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3128 - accuracy: 0.8727
Epoch 9/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3124 - accuracy: 0.8727
Epoch 10/100
7/7 [==============================] - 0s 3ms/step - loss: 0.3121 - accuracy: 0.8727
Epoch 11/100
7/7 [===========

In [55]:
ann.save('model.h5')
print('Saved model to disk')

Saved model to disk
