In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [20]:
data = pd.read_csv("breast-cancer-wisconsin-diagnosis.csv")
data.head()
data.dropna(inplace = True)

In [3]:
data.info()
data.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 702 entries, 0 to 701
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ID Number          699 non-null    float64
 1   Radius             699 non-null    float64
 2   Texture            699 non-null    float64
 3   Perimeter          699 non-null    float64
 4   Area               699 non-null    float64
 5   Smoothness         699 non-null    float64
 6   Compactness        699 non-null    float64
 7   Concavity          699 non-null    float64
 8   Concave Points     699 non-null    float64
 9   Symmetry           699 non-null    float64
 10  Fractal Dimension  699 non-null    float64
dtypes: float64(11)
memory usage: 60.5 KB


ID Number    Radius   Texture  Perimeter      Area  \
ID Number           1.000000 -0.080226 -0.055308  -0.041603 -0.041576   
Radius             -0.080226  1.000000  0.716001   0.817904  0.818934   
Texture            -0.055308  0.716001  1.000000   0.644913  0.654589   
Perimeter          -0.041603  0.817904  0.644913   1.000000  0.906882   
Area               -0.041576  0.818934  0.654589   0.906882  1.000000   
Smoothness         -0.064878  0.696800  0.486356   0.705582  0.683079   
Compactness        -0.045528  0.682785  0.521816   0.751799  0.719668   
Concavity          -0.089871  0.817653  0.589296   0.684569  0.704529   
Concave Points     -0.060051  0.756616  0.558428   0.755721  0.735948   
Symmetry           -0.052072  0.712244  0.535835   0.722865  0.719446   
Fractal Dimension  -0.034901  0.423170  0.350034   0.458693  0.438911   

                   Smoothness  Compactness  Concavity  Concave Points  \
ID Number           -0.064878    -0.045528  -0.089871       -0.060051   
Radius               0.696800     0.682785   0.817653        0.756616   
Texture              0.486356     0.521816   0.589296        0.558428   
Perimeter            0.705582     0.751799   0.684569        0.755721   
Area                 0.683079     0.719668   0.704529        0.735948   
Smoothness           1.000000     0.599599   0.665723        0.666715   
Compactness          0.599599     1.000000   0.582904        0.616102   
Concavity            0.665723     0.582904   1.000000        0.671545   
Concave Points       0.666715     0.616102   0.671545        1.000000   
Symmetry             0.603352     0.628881   0.572054        0.665878   
Fractal Dimension    0.417633     0.479101   0.342795        0.344169   

                   Symmetry  Fractal Dimension  
ID Number         -0.052072          -0.034901  
Radius             0.712244           0.423170  
Texture            0.535835           0.350034  
Perimeter          0.722865           0.458693  
Area               0.719446           0.438911  
Smoothness         0.603352           0.417633  
Compactness        0.628881           0.479101  
Concavity          0.572054           0.342795  
Concave Points     0.665878           0.344169  
Symmetry           1.000000           0.428336  
Fractal Dimension  0.428336           1.000000

In [23]:
X = data.iloc[:, 2:].values
y = data.iloc[:, 1].values

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [25]:
print(X_train)

[[10.  4.  4. ...  2.  3.  1.]
 [ 9. 10. 10. ...  3.  3.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]
 ...
 [ 4.  1.  1. ...  1.  1.  1.]
 [ 5.  1.  1. ...  2.  1.  1.]
 [ 1.  1.  1. ...  1.  1.  1.]]


In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
from sklearn.decomposition import PCA
dime = PCA(n_components=2)
X_train = dime.fit_transform(X_train)
X_test = dime.transform(X_test)

In [28]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [29]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[2. 2.]
 [2. 2.]
 [4. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [4. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 4.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [4. 4.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [4. 4.]
 

In [30]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[81  4]
 [ 1 54]]


0.9642857142857143