In [47]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [48]:
data = pd.read_csv("student-performance.csv")

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  395 non-null    int64  
 1   sex         395 non-null    float64
 2   age         395 non-null    int64  
 3   address     395 non-null    float64
 4   famsize     395 non-null    float64
 5   Pstatus     395 non-null    float64
 6   Medu        395 non-null    int64  
 7   Fedu        395 non-null    int64  
 8   Mjob        395 non-null    float64
 9   Fjob        395 non-null    float64
 10  reason      395 non-null    float64
 11  guardian    395 non-null    float64
 12  traveltime  395 non-null    int64  
 13  studytime   395 non-null    int64  
 14  failures    395 non-null    int64  
 15  schoolsup   395 non-null    float64
 16  famsup      395 non-null    float64
 17  paid        395 non-null    float64
 18  activities  395 non-null    float64
 19  nursery     395 non-null    f

In [50]:
data.head()

Unnamed: 0  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  \
0           0  0.0   18      1.0      0.0      0.0     4     4   0.0   4.0   
1           1  0.0   17      1.0      0.0      1.0     1     1   0.0   2.0   
2           2  0.0   15      1.0      1.0      1.0     1     1   0.0   2.0   
3           3  0.0   15      1.0      0.0      1.0     4     2   1.0   3.0   
4           4  0.0   16      1.0      0.0      1.0     3     3   2.0   2.0   

   ...  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  score  
0  ...       4         3      4     1     1       3         6   5   6      6  
1  ...       5         3      3     1     1       3         4   5   5      6  
2  ...       4         3      2     2     3       3        10   7   8     10  
3  ...       3         2      2     1     1       5         2  15  14     15  
4  ...       4         3      2     1     2       5         4   6  10     10  

[5 rows x 33 columns]

In [51]:
data.columns

Index(['Unnamed: 0', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu',
       'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'score'],
      dtype='object')

In [52]:
data.corr()

Unnamed: 0       sex       age   address   famsize   Pstatus  \
Unnamed: 0    1.000000 -0.075995  0.758057 -0.224469  0.016317  0.064132   
sex          -0.075995  1.000000 -0.028606 -0.028504  0.089862  0.023443   
age           0.758057 -0.028606  1.000000 -0.146722  0.037847  0.029598   
address      -0.224469 -0.028504 -0.146722  1.000000  0.072472 -0.042572   
famsize       0.016317  0.089862  0.037847  0.072472  1.000000 -0.149612   
Pstatus       0.064132  0.023443  0.029598 -0.042572 -0.149612  1.000000   
Medu         -0.160788  0.078228 -0.163658  0.138804 -0.043068 -0.123565   
Fedu         -0.123062  0.034878 -0.163438  0.072178 -0.058879 -0.088730   
Mjob         -0.056216  0.191421 -0.069104  0.108818  0.071386 -0.054476   
Fjob         -0.019385  0.084957 -0.035191 -0.001911 -0.084448  0.033892   
reason       -0.050395 -0.095867 -0.015337 -0.047891 -0.019212 -0.003553   
guardian      0.149409 -0.071343  0.290485 -0.044512 -0.002718 -0.108715   
traveltime    0.134816  0.059722  0.070641 -0.328096  0.063493  0.028265   
studytime     0.048421 -0.306268 -0.004140 -0.020912 -0.073595  0.024294   
failures      0.026426  0.044436  0.243665 -0.078578 -0.015769 -0.003339   
schoolsup    -0.295235 -0.138271 -0.251811  0.024712 -0.028642 -0.042238   
famsup       -0.185588 -0.151623 -0.140609  0.023903 -0.112893  0.019067   
paid          0.037921 -0.129126 -0.035933  0.052800 -0.013882  0.046435   
activities   -0.112805  0.099833 -0.103063 -0.051360 -0.000113  0.097352   
nursery      -0.098433 -0.008203 -0.086632  0.059589  0.102088 -0.090615   
higher       -0.046785 -0.151056 -0.209081  0.042854 -0.005806 -0.040735   
internet     -0.050290  0.044113 -0.112094  0.216842  0.000720  0.070074   
romantic      0.181496 -0.102023  0.164669  0.005257  0.034395 -0.040451   
famrel       -0.016190  0.058971  0.053940  0.014258 -0.022776  0.025179   
freetime      0.003895  0.238744  0.016434  0.034878  0.017695  0.038717   
goout         0.068811  0.075897  0.126964  0.068835  0.023064  0.003459   
Dalc          0.086302  0.268171  0.131125 -0.093494  0.101521 -0.030590   
Walc          0.095454  0.274194  0.117276 -0.101126  0.103425  0.006045   
health       -0.088902  0.143588 -0.062187 -0.040355 -0.028992  0.022307   
absences      0.065966 -0.066962  0.175230 -0.027874  0.035783 -0.134937   
G1            0.046963  0.091839 -0.064081  0.069704  0.071445 -0.016868   
G2           -0.053344  0.091099 -0.143474  0.126037  0.081223 -0.041382   
score        -0.099991  0.103456 -0.161579  0.105756  0.081407 -0.058009   

                Medu      Fedu      Mjob      Fjob  ...    famrel  freetime  \
Unnamed: 0 -0.160788 -0.123062 -0.056216 -0.019385  ... -0.016190  0.003895   
sex         0.078228  0.034878  0.191421  0.084957  ...  0.058971  0.238744   
age        -0.163658 -0.163438 -0.069104 -0.035191  ...  0.053940  0.016434   
address     0.138804  0.072178  0.108818 -0.001911  ...  0.014258  0.034878   
famsize    -0.043068 -0.058879  0.071386 -0.084448  ... -0.022776  0.017695   
Pstatus    -0.123565 -0.088730 -0.054476  0.033892  ...  0.025179  0.038717   
Medu        1.000000  0.623455  0.454805  0.157920  ... -0.003914  0.030891   
Fedu        0.623455  1.000000  0.243327  0.200169  ... -0.001370 -0.012846   
Mjob        0.454805  0.243327  1.000000  0.196758  ...  0.038584  0.114321   
Fjob        0.157920  0.200169  0.196758  1.000000  ...  0.013709 -0.047475   
reason      0.117653  0.043099  0.022022 -0.027688  ... -0.014934 -0.066834   
guardian   -0.023918 -0.133644  0.014787 -0.080511  ...  0.040979  0.045716   
traveltime -0.171639 -0.158194 -0.109752  0.055878  ... -0.016808 -0.017025   
studytime   0.064944 -0.009175 -0.023097 -0.076817  ...  0.039731 -0.143198   
failures   -0.236680 -0.250408 -0.073377 -0.008275  ... -0.044337  0.091987   
schoolsup  -0.036029  0.037530 -0.040958 -0.011657  ... -0.001345 -0.045465   
famsup      0.183727  0.185496  0.050667 -0.030159  ... -0.020436  0.010538   
paid 

In [53]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

In [54]:
print(X)

[[ 0. 18.  1. ...  6.  5.  6.]
 [ 0. 17.  1. ...  4.  5.  5.]
 [ 0. 15.  1. ... 10.  7.  8.]
 ...
 [ 1. 21.  0. ...  3. 10.  8.]
 [ 1. 18.  0. ...  0. 11. 12.]
 [ 1. 19.  1. ...  5.  8.  9.]]


In [55]:
print(y)

[ 6  6 10 15 10 15 11  6 19 15  9 12 14 11 16 14 14 10  5 10 15 15 16 12
  8  8 11 15 11 11 12 17 16 12 15  6 18 15 11 13 11 12 18 11  9  6 11 20
 14  7 13 13 10 11 13 10 15 15  9 16 11 11  9  9 10 15 12  6  8 16 15 10
  5 14 11 10 10 11 10  5 12 11  6 15 10  8  6 14 10  7  8 18  6 10 14 10
 15 10 14  8  5 17 14  6 18 11  8 18 13 16 19 10 13 19  9 16 14 13  8 13
 15 15 13 13  8 12 11  9  0 18  0  0 12 11  0  0  0  0 12 15  0  9 11 13
  0 11  0 11  0 10  0 14 10  0 12  8 13 10 15 12  0  7  0 10  7 12 10 16
  0 14  0 16 10  0  9  9 11  6  9 11  8 12 17  8 12 11 11 15  9 10 13  9
  8 10 14 15 16 10 18 10 16 10 10  6 11  9  7 13 10  7  8 13 14  8 10 15
  4  8  8 10  6  0 17 13 14  7 15 12  9 12 14 11  9 13  6 10 13 12 11  0
 12 12  0 12  0 18 13  8  5 15  8 10  8  8 12  8 13 11 14  0 18  8 12  9
  0 17 10 11 10  0  9 14 11 14 10 12  9  9  8 10  8 10 12 10 11 11 19 12
 14 15 11 15 13 18 14 11  0  8 14 16 11 10 14 18 13 12 18  8 12 10  0 13
 11 11 13 11  0  9 10 11 13  9 11 15 15 11 16 10  9

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [57]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state=0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [58]:
y_pred = regressor.predict(X_test)

In [59]:
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

array([[ 6.,  0.],
       [10., 10.],
       [ 9.,  8.],
       [ 9., 10.],
       [ 9., 10.],
       [11., 12.],
       [ 6.,  8.],
       [12., 11.],
       [12., 11.],
       [ 8.,  8.],
       [11., 11.],
       [14., 13.],
       [ 8.,  8.],
       [ 8.,  7.],
       [ 9., 10.],
       [12., 10.],
       [16., 15.],
       [15., 16.],
       [ 6.,  8.],
       [10., 10.],
       [11., 11.],
       [18., 19.],
       [10., 10.],
       [12., 11.],
       [15., 16.],
       [ 6.,  5.],
       [10., 11.],
       [ 8.,  9.],
       [ 9., 10.],
       [13., 13.],
       [12., 12.],
       [12., 11.],
       [ 9., 10.],
       [11., 11.],
       [12., 14.],
       [ 8.,  8.],
       [11., 10.],
       [10., 10.],
       [ 8.,  7.],
       [12., 10.],
       [ 9.,  9.],
       [11.,  9.],
       [18., 15.],
       [11.,  9.],
       [11., 11.],
       [11., 13.],
       [18., 18.],
       [10.,  9.],
       [15., 14.],
       [ 9., 10.],
       [ 6.,  5.],
       [12., 10.],
       [12.,

In [60]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.7268710592316527